package Interface;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JPanel;
import javax.swing.JTextField;
import mastertv.Canal;
import mastertv.Categoria;
import mastertv.Contrato;
import mastertv.PlanoIlimitado;

public class EscolherCategorias extends javax.swing.JFrame {

    TelaContrato contrato;
    public EscolherCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbCategoria1 = new javax.swing.JComboBox<>();
        cbCategoria2 = new javax.swing.JComboBox<>();
        cbCategoria3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pConfirmar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pCancelar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pPreco = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ftPreco = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Escolher Categorias");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tv-Master");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(444, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 90));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbCategoria1.setBorder(null);
        jPanel2.add(cbCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 27, -1, -1));

        jPanel2.add(cbCategoria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 26, -1, -1));

        cbCategoria3.setBorder(null);
        jPanel2.add(cbCategoria3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 27, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Preço");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 91, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 70, 10));

        pConfirmar.setBackground(new java.awt.Color(0, 51, 51));
        pConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pConfirmarMouseExited(evt);
            }
        });
        pConfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirmar");
        pConfirmar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel2.add(pConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 204, 142, 40));

        pCancelar.setBackground(new java.awt.Color(0, 102, 102));
        pCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCancelarMouseClicked(evt);
            }
        });
        pCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 51));
        jLabel7.setText("Cancelar");
        pCancelar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(pCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 207, -1, 37));

        pPreco.setBackground(new java.awt.Color(0, 51, 51));
        pPreco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPrecoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pPrecoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pPrecoMouseExited(evt);
            }
        });
        pPreco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ver Preço");
        pPreco.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel2.add(pPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 204, 142, 40));

        ftPreco.setEditable(false);
        ftPreco.setBackground(jPanel2.getBackground());
        ftPreco.setForeground(new java.awt.Color(255, 255, 255));
        ftPreco.setBorder(null);
        jPanel2.add(ftPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 630, 270));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 630, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pConfirmarMouseEntered
        setColor(pConfirmar);
    }//GEN-LAST:event_pConfirmarMouseEntered

    private void pConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pConfirmarMouseExited
        resetColor(pConfirmar);
    }//GEN-LAST:event_pConfirmarMouseExited

    private void pCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCancelarMouseClicked
        contrato.dispose();
        this.dispose();
    }//GEN-LAST:event_pCancelarMouseClicked

    private void pConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pConfirmarMouseClicked
        int selected;
        Contrato con = new Contrato();
        con.setAcesso(true);
        con.setEndereco(contrato.gettEndereco().getText());
        con.setNumeroReceptores(Integer.parseInt(contrato.getFtReceptores().getText()));
        con.setCpf(contrato.getMenu().gettCpf().getText());
        if(contrato.getRbTop().isSelected()){
            con.setPlano(1);
            con.setCategorias(new int[2]);
        }
        else if(contrato.getRbRegular().isSelected()){
            con.setPlano(2);
            con.setCategorias(new int[3]);
        }
        else if(contrato.getRbIlimitado().isSelected()){
            con.setMensalidade(PlanoIlimitado.calcularMensalidade());
            con.setCategorias(null);
            con.setPlano(3);
        }
        
        Categoria c = new Categoria();
        if((cbCategoria1.getSelectedIndex() != cbCategoria2.getSelectedIndex()) &&
          (cbCategoria2.getSelectedIndex() != cbCategoria3.getSelectedIndex()) &&
          (cbCategoria1.getSelectedIndex() != cbCategoria3.getSelectedIndex())){
            selected = cbCategoria1.getSelectedIndex();
            c.setNome(cbCategoria1.getItemAt(selected));
            c.getFromDB();
            con.setMensalidade(Canal.getSumAllPreco(c.getId()));
            con.getCategorias()[0] = c.getId();
            selected = cbCategoria2.getSelectedIndex();
            c.setNome(cbCategoria2.getItemAt(selected));
            c.getFromDB();
            con.setMensalidade(con.getMensalidade()+Canal.getSumAllPreco(c.getId()));
            con.getCategorias()[1] = c.getId();
            if(cbCategoria3.isVisible()){
                selected = cbCategoria3.getSelectedIndex();
                c.setNome(cbCategoria3.getItemAt(selected));
                c.getFromDB();
                con.setMensalidade(con.getMensalidade()+Canal.getSumAllPreco(c.getId()));
                con.getCategorias()[2] = c.getId();
            }
            if(con.addOnDb()) JOptionPane.showMessageDialog(rootPane, "Contrato Feito Sucesso","Sucesso!", INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao tentar fazer o contrato", "Erro!", ERROR_MESSAGE);
            contrato.dispose();
            this.dispose();
        }else if(cbCategoria1.getSelectedIndex() == -1 && cbCategoria2.getSelectedIndex() == -1 && cbCategoria3.getSelectedIndex()== -1){
            if(con.addOnDb()) JOptionPane.showMessageDialog(rootPane, "Contrato Feito Sucesso","Sucesso!", INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao tentar fazer o contrato", "Erro!", ERROR_MESSAGE);
            contrato.dispose();
            this.dispose();
        }
        else JOptionPane.showMessageDialog(rootPane, "Categorias Ecolhidas Iguais", "Erro!", ERROR_MESSAGE);
    }//GEN-LAST:event_pConfirmarMouseClicked

    private void pPrecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPrecoMouseClicked
        if((cbCategoria1.getSelectedIndex() != cbCategoria2.getSelectedIndex()) &&
          (cbCategoria2.getSelectedIndex() != cbCategoria3.getSelectedIndex()) &&
          (cbCategoria1.getSelectedIndex() != cbCategoria3.getSelectedIndex())){
            Categoria c = new Categoria();
            int selected;
            float preco = 0;
            selected = cbCategoria1.getSelectedIndex();
            c.setNome(cbCategoria1.getItemAt(selected));
            c.getFromDB();
            preco += Canal.getSumAllPreco(c.getId());
            selected = cbCategoria2.getSelectedIndex();
            c.setNome(cbCategoria2.getItemAt(selected));
            c.getFromDB();
            preco += Canal.getSumAllPreco(c.getId());
            if(cbCategoria3.isVisible()){
                selected = cbCategoria3.getSelectedIndex();
                c.setNome(cbCategoria3.getItemAt(selected));
                c.getFromDB();
                preco += Canal.getSumAllPreco(c.getId());
            }
            ftPreco.setText(Float.toString(preco));
        }else if(cbCategoria1.getSelectedIndex() == -1 && cbCategoria2.getSelectedIndex() == -1 && cbCategoria3.getSelectedIndex()== -1){
            ftPreco.setText(Float.toString(PlanoIlimitado.calcularMensalidade()));
        }
    }//GEN-LAST:event_pPrecoMouseClicked

    private void pPrecoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPrecoMouseEntered
        setColor(pPreco);
    }//GEN-LAST:event_pPrecoMouseEntered

    private void pPrecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPrecoMouseExited
        resetColor(pPreco);
    }//GEN-LAST:event_pPrecoMouseExited

    public JTextField getFtPreco() {
        return ftPreco;
    }

    public void setFtPreco(JFormattedTextField ftPreco) {
        this.ftPreco = ftPreco;
    }

    public TelaContrato getContrato() {
        return contrato;
    }

    public void setContrato(TelaContrato contrato) {
        this.contrato = contrato;
    }

    public JComboBox<String> getCbCategoria1() {
        return cbCategoria1;
    }

    public void setCbCategoria1(JComboBox<String> cbCategoria1) {
        this.cbCategoria1 = cbCategoria1;
    }

    public JComboBox<String> getCbCategoria2() {
        return cbCategoria2;
    }

    public void setCbCategoria2(JComboBox<String> cbCategoria2) {
        this.cbCategoria2 = cbCategoria2;
    }

    public JComboBox<String> getCbCategoria3() {
        return cbCategoria3;
    }

    public void setCbCategoria3(JComboBox<String> cbCategoria3) {
        this.cbCategoria3 = cbCategoria3;
    }

    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(0,153,153));
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(0,51,51));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolherCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategoria1;
    private javax.swing.JComboBox<String> cbCategoria2;
    private javax.swing.JComboBox<String> cbCategoria3;
    private javax.swing.JTextField ftPreco;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pCancelar;
    private javax.swing.JPanel pConfirmar;
    private javax.swing.JPanel pPreco;
    // End of variables declaration//GEN-END:variables
}
