/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JPanel;
import mastertv.Chamado;
import mastertv.Funcionario;

/**
 *
 * @author Luís
 */
public class TelaChamado extends javax.swing.JFrame {

    /**
     * Creates new form Chamado
     */
    public TelaChamado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lContrato = new javax.swing.JLabel();
        lMotivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMotivo = new javax.swing.JTextArea();
        pChamado = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pCancelar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbTecnicos = new javax.swing.JComboBox<>();
        lTecnico = new javax.swing.JLabel();
        cbContratos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tv-Master");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/phone-auricular-with-high-volume.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 130, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 540));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Chamado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, -1, -1));

        lContrato.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lContrato.setForeground(new java.awt.Color(255, 255, 255));
        lContrato.setText("Nº Contrato");
        jPanel2.add(lContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        lMotivo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lMotivo.setForeground(new java.awt.Color(255, 255, 255));
        lMotivo.setText("Motivo");
        jPanel2.add(lMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        tMotivo.setBackground(jPanel2.getBackground());
        tMotivo.setColumns(20);
        tMotivo.setForeground(new java.awt.Color(255, 255, 255));
        tMotivo.setLineWrap(true);
        tMotivo.setTabSize(4);
        tMotivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tMotivo.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tMotivo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 300, 110));

        pChamado.setBackground(new java.awt.Color(0, 102, 102));
        pChamado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pChamadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pChamadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pChamadoMouseExited(evt);
            }
        });
        pChamado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Efetuar Chamado");
        pChamado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(pChamado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 180, 40));

        pCancelar.setBackground(new java.awt.Color(0, 51, 51));
        pCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCancelarMouseClicked(evt);
            }
        });
        pCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 51));
        jLabel8.setText("Cancelar");
        pCancelar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(pCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 70, 40));

        cbTecnicos.setForeground(new java.awt.Color(255, 255, 255));
        cbTecnicos.setBorder(null);
        jPanel2.add(cbTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        lTecnico.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lTecnico.setForeground(new java.awt.Color(255, 255, 255));
        lTecnico.setText("Tecnico");
        jPanel2.add(lTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        cbContratos.setForeground(new java.awt.Color(255, 255, 255));
        cbContratos.setBorder(null);
        jPanel2.add(cbContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 400, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pChamadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pChamadoMouseEntered
        setColor(pChamado);
    }//GEN-LAST:event_pChamadoMouseEntered

    private void pChamadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pChamadoMouseExited
        resetColor(pChamado);
    }//GEN-LAST:event_pChamadoMouseExited

    private void pCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_pCancelarMouseClicked

    private void pChamadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pChamadoMouseClicked
        lMotivo.setForeground(Color.white);
        lContrato.setForeground(Color.white);
        lTecnico.setForeground(Color.white);
        if(tMotivo.getText().isEmpty() || tMotivo.getText().length()>80){
            JOptionPane.showMessageDialog(rootPane, "Motivo não preenchido ou texto muito grande", "Erro!", ERROR_MESSAGE);
            lMotivo.setForeground(Color.red);
            if(cbContratos.getSelectedIndex() == -1){
                JOptionPane.showMessageDialog(rootPane, "Nenhum contrato foi selecionado", "Erro!", ERROR_MESSAGE);
                lContrato.setForeground(Color.red);
            }
            if(cbTecnicos.getSelectedIndex() == -1){
                JOptionPane.showMessageDialog(rootPane, "Nenhum Tecnico foi selecionado", "Erro!", ERROR_MESSAGE);
                lTecnico.setForeground(Color.red);
            }
            return;
        }
        else if(cbContratos.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(rootPane, "Nenhum contrato foi selecionado", "Erro!", ERROR_MESSAGE);
            lContrato.setForeground(Color.red);
            if(cbTecnicos.getSelectedIndex() == -1){
                JOptionPane.showMessageDialog(rootPane, "Nenhum Tecnico foi selecionado", "Erro!", ERROR_MESSAGE);
                lTecnico.setForeground(Color.red);
            }
            return;
        }
        else if(cbTecnicos.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(rootPane, "Nenhum Tecnico foi selecionado", "Erro!", ERROR_MESSAGE);
            lTecnico.setForeground(Color.red);
            return;
        }
        Chamado c = new Chamado();
        Funcionario f = new Funcionario();
        f.getFromDB();
        f.setUsuario(cbTecnicos.getItemAt(cbTecnicos.getSelectedIndex()));
        f.getFromDB();
        c.setMotivo(tMotivo.getText());
        c.setIdtecnicos(f.getIdFuncionario());
        c.setContrato(Integer.parseInt(cbContratos.getItemAt(cbContratos.getSelectedIndex())));
        c.setSituacao("Aberto");
        if(c.addOnDb()) {
            JOptionPane.showMessageDialog(rootPane, "Chamado Feito com Sucesso","Sucesso!", INFORMATION_MESSAGE);
            this.dispose();
        }
        else  JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao fazer o chamdo!", "Erro!", ERROR_MESSAGE);
    }//GEN-LAST:event_pChamadoMouseClicked

    public JComboBox<String> getCbTecnicos() {
        return cbTecnicos;
    }

    public void setCbTecnicos(JComboBox<String> cbTecnicos) {
        this.cbTecnicos = cbTecnicos;
    }

    public JComboBox<String> getCbContratos() {
        return cbContratos;
    }

    public void setCbContratos(JComboBox<String> cbContratos) {
        this.cbContratos = cbContratos;
    }

    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(0,153,153));
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(0,102,102));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaChamado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbContratos;
    private javax.swing.JComboBox<String> cbTecnicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lContrato;
    private javax.swing.JLabel lMotivo;
    private javax.swing.JLabel lTecnico;
    private javax.swing.JPanel pCancelar;
    private javax.swing.JPanel pChamado;
    private javax.swing.JTextArea tMotivo;
    // End of variables declaration//GEN-END:variables
}
